:PROPERTIES:
:ID:       aef22b38-8936-4c1c-8f0d-0882e4399c95
:END:
#+title: Hoi Suc Tim Mach

* Chẩn đoán hình ảnh
  [[id:67b3077c-eb16-4906-94d0-33b95b7d4a75][Chan Doan Hinh Anh]] 

* Tham khảo thêm
  1. [[id:6688141a-11fe-4509-8c37-059487ea96f4][Inotropes and vasopressors]]
* Books
** Cardiothoracic critical care
*** Chap1 - The normal postoperative cardiac patient
**** Introducion
     1. 
**** Effects of surgery and cardiopulmonary bypass
     1. Inflammatory response
     2. Cooling
     3. Pulmonary effects
     4. 
**** Typical progression
     1. 
**** Routine mangement
     - The majority of patients require minimal intervention and are best served by following routine protocols.
       1) Ventilation
       2) Re-warming
       3) Inotropes and vasopressors
       4) Fluid and electrolyte management
       5) Analgesia and antiemesis
**** Warning signs
*** Chap2 - Risk prediction and outcome
*** Chap3 - Fast tracking the low-risk patient
**** Fast-track concepts
*** Chap4 - Resusciation in the cardiac intensive care setting
**** Cardiac Surgery Advanced Life Support
     1. 
*** Chap9 - Postoperative medications
**** Postoperative medications
     1. Antibiotic prophylaxis
     2. Stress ulcer prophylaxis
     3. Electrolytes
     4. Antiemetics
     5. Shivering
     6. Glucose control
     7. Deep venous thrombosis prophylaxis
     8. Arrhythmia (atrial fibrillation) prophylaxi
*** Chap11 - Heart dysfunction
**** Left ventricular failure
     1. Đánh giá chức năng thất trái: Cardiac output + anatomical and functional assessment
     2. Điều trị: Thuốc, hỗ trợ cơ học: IABP counterpulsation, short-term VADs, long-term VDAs, ECMO. 
**** Right ventrical failure
     1. Anatomy and physiology of the RV
	- the RV contracts in a peristaltic pattern from the sinus to the infundibulum. It relies on longitudinal shortening more than the LV.
	- the RV wraps around the LV: *up to 30% of the contractile energy of the RV is generated by the LV.*
	- the LV and RV are enclosed in a non-expanding pericardium. *Overdistention of the RV within this closed sac compromises LV contractile performance primarily by reducing LV preload.*
	- RV is exquisitely volume sensitive.
	- the RVs response to i preload or afterload is overdistention.
     2. Management: general principles
	- Optimize ventilation
	- Maintain sinus rhythm (aim for HR 90–110bpm)
	- OPtimize preload: tối ưu dịch, thuốc, surgical
	- Reduce afterload: pulmonary vasodilator, minimize blood prodcution transfution.
	- *Key point*: In acute RV failure, every effort should be made to avoid systemic hypotension, which may lead to a vicious cycle of RV ischaemia and further hypotension.
	- Xem thêm: [[id:de47db73-ef8f-45a9-b6aa-2ce08559556b][Right Ventrical Assessment]]
	- 
*** Chap12 - Lung dysfunction
**** Acute lung injury/ acute respiratory distress syndrome
     1. Introduction
	- Acute respiratory distress syndrome (ArDS) is a clinical condition comprising respiratory distress, hypoxaemia refractory to oxygen, d lung compliance, and the appearance of diffuse infiltrates on a CXR.
     2. Chẩn đoán
	- Xem thêm: [[https://introductiontoradiology.net/courses/rad/chest/f19ardsVsChf.html][ARDS versus Congestive Heart Failure]]
	  + Features that are helpful in distinguishing CHF from ARDS include the following: While cardiogenic pulmonary edema typically begins *centrally in the bilateral perihilar areas*, ARDS usually causes more uniform opacification. *Pleural effusions* are not typical of ARDS but often present in CHF. *Kerley B lines* are common in CHF but not in ARDS, while air bronchograms can be found in both.
	  + *Temporally, radiographic abnormalities usually closely parallel cardiogenic pulmonary edema, while the chest radiograph in ARDS may remain unremarkable for up to twelve hours and usually stabilize after the first thirty-six hours*. *While radiographic findings in cardiogenic edema may clear rapidly, ARDS typically clears slowly*. Unlike cardiogenic edema, which, once resolved, does not leave behind permanent pulmonary changes, a percentage of ARDS cases will result in some degree of permanent pulmonary fibrosis, characterized by increased intersitital markings depending on the severity and length of time the patient was in ARDS.
	- Xem thêm [[https://ccforum.biomedcentral.com/articles/10.1186/s13054-017-1809-8][A systematic review of diagnostic methods to differentiate acute lung injury/acute respiratory distress syndrome from cardiogenic pulmonary edema]]
	- 
*** Chap13 - Kidney dysfunction
*** Chap18 - The thoracic patient
*** Chap21 - Heart failure resistant
**** Assessment
     1. Clarify diagnosis:
	- Is this heart failure or a mimic?
	- Has heart failure been diagnosed previously?
	- Is there dual pathology? e.g. heart failure and pneumonia.
     2. Try to define cause for decompensation or acute presentation:
	- Symptoms of ischaemia, arrhythmia, hypotension
	- Recent medication changes or compliance issues
	- Cardiotoxic drugs or drugs that may exacerbate fluid retention
	- Non-adherence to fluid, salt, or alcohol restriction
	- Beware of the ‘nil by mouth’ surgical patient. Has cardiac medication been withheld? Has patient received excessive IV fluid?
*** Chap24 - Central venous cannulation, pulmonary artery catheter, and minimally invase cardiac output monitoring
**** 
* Tình huống lâm sàng tưởng tượng
