* Lời mở đầu
  - Một buổi chiều đầu tháng 3 năm 2025, Khoa Nội Tim mạch - Tim mạch can thiệp chúng tôi tiếp nhận một trường hợp từ Khoa Cấp cứu. Bệnh nhân nam trung niên nhập viện trong tình trạng trong tình trạng nguy kịch: đau ngực, khó thở, huyết áp tụt và rối loạn nhịp tim nguy hiểm. Nhận định đây là trường hợp nhồi máu cơ tim đã có biểu hiện tiền sốc tim, rối loạn nhịp nguy cơ ngừng tim cao, cần điều trị tái thông mạch máu bị tắc khẩn cấp. Chúng tôi tiến hành điều trị nội khoa cấp cứu ban đầu, giải thích tình trạng bệnh cho người bệnh và thân nhân, sau đó tiến hành can thiệp khẩn cấp nong và đặt thành công 02 stent động mạch vành. Nếu không được can thiệp tim mạch kịp thời, dù người bệnh có thể qua được cơn nguy kịch đi chăng nữa, thì nhiều khả năng sức khỏe sẽ bị giảm sút nghiêm trọng dẫn đến mất sức lao động, thậm chí tàn phế phải sống phụ thuộc vào người thân. Nhờ được can thiệp tim mạch kịp thời, người bệnh sau đó hồi phục nhanh chóng, hết đau ngực, hết khó thở, khỏe dần lên sau vài ngày, cuộc sống trở về gần như bình thường không lâu sau đó. Đây là một trong nhiều câu chuyện  minh chứng sống động cho thế mạnh tuyệt vời của tim mạch can thiệp – nơi chúng tôi không chỉ can thiệp vào mạch máu, mà còn mang lại nhịp sống mới cho mỗi người.
  - Bệnh tim mạch ngày nhiều và càng trẻ hóa dần, gánh nặng sức khỏe và kinh tế của nó là rất lớn. Việc phát hiện bệnh tim mạch sớm và điều trị phù hợp là chìa khóa tối quan trọng để đảm bảo một cuộc sống chất lượng tốt và khả năng lao động lâu dài. Những khách hàng dường như "khỏe mạnh" đến với Khoa Nội Tim mạch - Tim mạch can thiệp sẽ được thăm khám và thực hiện các khảo nghiệm cận lâm sàng để phát hiện bệnh ở giai đoạn sớm nhất, và tốt hơn nữa là phát hiện và ngăn ngừa những nguy cơ tiềm ẩn khi nó chưa phát triển thành bệnh. 
  - Khoa Nội Tim mạch - Tim mạch can thiệp Bệnh viện Hồng Đức II chúng tôi có đội ngũ chuyên gia bác sĩ và điều dưỡng và kỹ thuật viên hiểu rõ về sức khỏe trái tim, có đầy đủ các thiết bị chẩn đoán điều trị từ cơ bản đến chuyên sâu, từ khu điều trị nội trú ven sông yên bình đến hệ thống phòng bệnh hiện đại, chúng tôi tạo ra một môi trường lý tưởng để bệnh nhân không chỉ chữa bệnh mà còn an tâm nghỉ dưỡng, phục hồi.
* Hoạt động chuyên môn và cơ sở vật chất, trang thiết bị
    1. Phòng khám chuyên khoa tim mạch
       - Khám và điều trị ngoại trú các bệnh lý tim mạch ổn định. Theo dõi các bệnh nhân nội trú đã được xuất viện.
       - Phòng khám được hỗ trợ bởi hệ thống xét nghiệm chuyên sâu và hiện đại cho kết quả nhanh và chính xác; hệ thống chẩn đoán hình ảnh tiên tiến gồm điện tim, siêu âm tim, siêu âm mạch máu, X quang, máy CT 128 lát cắt, máy cộng hưởng từ 3 tesla cho tốc độ chụp nhanh, hình ảnh sắc nét, giúp phát hiện rất sớm các bệnh lý nguy hiểm trên khắp cơ thể.
    2. Khu điều trị nội trú tim mạch
       - Phòng theo dõi bệnh nặng với hệ thống Oxy trung tâm hiện đại, hệ thống monitor theo dõi liên tục, hệ thống điện tim, siêu âm tim tại giường giúp bác sĩ theo dõi sát sao tình trạng của người bệnh và ra y lệnh điều trị kịp thời. 
       - Hệ thống phòng bệnh nội trú rộng rãi, yên tĩnh, sạch sẽ, với khung cảnh ven sông yên bình tạo cho người bệnh cảm giác thoải mái, vừa chữa bệnh đồng thời nghỉ dưỡng. Gồm có phòng bệnh VIP, phòng 2 giường và phòng 3 giường.
       - Một số trang thiết bị trong khu điều trị nội trú:
         + Máy mornitor theo dõi liên tục + huyết áp động mạch xâm lấn - Hãng Philips
         + Máy siêu âm tim tại giường - Hãng Phillips
         + Máy đo điện tim tại giường - Hãng Phillips
         + Máy Holter điện tim - Hãng Philips. 
    3. Phòng can thiệp tim mạch
      - Khoa Nội Tim mạch - Tim mạch can thiệp Bệnh viện Hồng Đức II được trang bị hệ thống phòng Hybrid hiện đại, trong đó DSA là một thành phần thiết yếu của một hệ thống phức hợp đa chức năng bao gồm chẩn đoán hình ảnh, phẫu thuật, và can thiệp mạch máu.
      - Kỹ thuật DSA giúp bác sĩ quan sát rõ nét hình ảnh mạch máu và hình ảnh dòng máu lưu thông trong lòng mạch theo thời gian thực, từ đó có thể đưa ra chẩn đoán nhiều bệnh lý mạch máu khác nhau với độ chính xác rất cao.
      - Cùng với sự phát triển cực kỳ tân tiến của các dụng cụ và kỹ thuật can thiệp trong lòng mạch máu mà những bệnh lý trước đây không thể điều trị được hoặc chỉ có thể điều trị bằng những cuộc phẫu thuật lớn thì hiện nay có thể thực hiện bằng cách đưa dụng cụ vào lòng mạch máu qua một ống thông rất nhỏ đến vị trí tổn thương, bác sĩ có thể quan sát và "sửa" trực tiếp tổn thương dựa vào hình ảnh trên máy DSA. Vì bác sĩ can thiệp chỉ đưa dụng cụ qua một ống thông rất nhỏ vào lòng mạch máu nên hạn chế được nhiều biến chứng liên quan đến những đường mổ lớn, giảm thời gian nằm viện, người bệnh ít cảm giác đau và không để lại sẹo lớn. 
      - Một số trang thiết bị trong phòng mổ Hybrid tại Bệnh viện Hồng Đức II:
        + Bộ hiển thị và xử lý trung tâm dùng cho hệ thống quản lý tim mạch trung tâm - AZurion 7 M20 của hãng Philips - Hà Lan
        + Máy chụp C-Arm - Endura của hãng Philips - Hà Lan
        + Hệ thống bàn GETINGE
        + Máy bơm bóng đối xung động mạch chủ Datascope Corp - Mỹ
        + Máy gây mê giúp thở Primus của hãng Dragerwerk AG&Co - Đức
        + Máy sốc tim FM100  của hãng Philips
        + Mornitor theo dõi bệnh nhân CM150 của hãng Philips
    4. Phòng điện tim gắng sức
       - Phòng điện tim gắng sức được trang bị hệ thống Philips hiên đại gồm thảm lăn có thể dừng khẩn cấp, hệ thống theo dõi điện tim, huyết áp, nồng độ oxy máu liên tục giúp bác sĩ phân tích các chỉ số sinh học khi người bệnh gắng sức từ đó có thể chẩn đoán các bệnh lý như thiếu máu cơ tim, rối loạn nhịp tim hoặc đánh giá khả năng gắng sức của người bệnh (sau nhồi máu cơ tim, sức khỏe vận động viên) và kê đơn vận động phù hợp. 
    5. Phòng laser nội mạch điều trị suy giãn tĩnh mạch mạn tính
       - Laser nội mạch là một phương pháp tiên tiến giúp điều trị suy giãn tĩnh mạch mạn tính, cải thiện triệu chứng và cải thiện thẩm mỹ bằng cách làm mờ hoặc loại bỏ các tĩnh mạch giãn nhìn thấy được. Người bệnh có thể vận động sớm nhẹ nhàng sau thủ thuật. 
       - Phòng được trang bị Oxy di động, máy monitor theo dõi liện tục, máy SPO2, máy siêu âm mạch máu di động Philips CX-50, máy laser nội mạch Venacure 1470
* Các dịch vụ kỹ thuật nổi bật
  - Chụp động mạch vành
    + Đây là thủ thuật sử dụng một ống nhỏ (catheter) luồn vào mạch máu ở tay hoặc chân, đưa lên tim. Sau đó, bác sĩ sẽ tiêm một loại thuốc cản quang đặc biệt vào động mạch vành (mạch máu nuôi tim) và chụp bằng hệ thống DSA. Công dụng: Giúp bác sĩ nhìn rõ hình ảnh bên trong các động mạch vành, phát hiện xem có chỗ nào bị hẹp, tắc nghẽn hoặc tổn thương không. Đây là "tiêu chuẩn vàng" để chẩn đoán bệnh mạch vành.
  - Nong và đặt stent động mạch vành
    + Sau khi xác định được chỗ hẹp hoặc tắc nghẽn qua chụp động mạch vành, bác sĩ sẽ sử dụng một quả bóng nhỏ để nong rộng lòng mạch (nong mạch). Sau đó, một cái lưới nhỏ hình ống (stent) sẽ được đặt vào vị trí đó để giữ cho mạch máu luôn mở, không bị hẹp lại. Công dụng: Giúp máu lưu thông bình thường qua chỗ hẹp, giảm các triệu chứng như đau ngực, khó thở khi gắng sức, cải thiện tiên lượng và ngăn ngừa các biến cố tim mạch nguy hiểm như nhồi máu cơ tim.
  - Chụp MSCT mạch vành có tiêm thuốc cản quang
    + Đây là kỹ thuật chụp cắt lớp vi tính đa dãy (Multi-slice Computed Tomography - MSCT) kết hợp với việc tiêm thuốc cản quang vào tĩnh mạch. Thuốc sẽ đi vào các mạch máu, giúp máy chụp tạo ra hình ảnh 3D chi tiết của động mạch vành. Công dụng: Giúp đánh giá sơ bộ tình trạng động mạch vành, tìm kiếm các mảng xơ vữa hoặc hẹp đáng kể. Kỹ thuật này ít xâm lấn hơn chụp động mạch vành và thường được dùng để tầm soát hoặc loại trừ bệnh mạch vành ở những trường hợp nguy cơ thấp và trung bình.
  - Holter điện tâm đồ
    + Một thiết bị nhỏ gọn có các điện cực được gắn vào ngực để ghi lại hoạt động điện của tim liên tục trong 24 giờ hoặc hơn, trong khi người bệnh vẫn sinh hoạt bình thường. Công dụng: giúp phát hiện các rối loạn nhịp mà điện tim một thòi điểm không phát hiện được.
  - Đặt máy tạo nhịp tạm thời
    + Là thủ thuật đưa một dây điện cực nhỏ vào tim thông qua tĩnh mạch, dây này được nối với một máy tạo nhịp bên ngoài cơ thể. Máy sẽ phát ra các xung điện để điều hòa nhịp tim. Công dụng: Dùng trong các trường hợp cấp cứu khi nhịp tim quá chậm giúp ổn định nhịp tim tạm thời cho đến khi tìm được giải pháp lâu dài hoặc tình trạng bệnh nhân cải thiện, một số trường hợp dùng điều trị cắt cơn nhịp nhanh
  - Đặt máy tạo nhịp vĩnh viễn
    + Là thủ thuật cấy ghép một thiết bị nhỏ gọn (bằng hộp diêm) dưới da vùng ngực. Thiết bị này có một hoặc nhiều dây điện cực nối vào tim, liên tục theo dõi nhịp tim và phát ra các xung điện khi cần để duy trì nhịp tim ổn định. Công dụng: Điều trị lâu dài cho những người có nhịp tim quá chậm hoặc rối loạn nhịp tim nghiêm trọng không thể điều trị bằng thuốc, giúp cải thiện chất lượng cuộc sống và phòng ngừa các biến chứng do nhịp tim bất thường.
  - Điện tâm đồ gắng sức
    + Người bệnh sẽ được gắn các điện cực vào ngực để theo dõi hoạt động điện của tim, tương tự như đo điện tâm đồ thông thường. Tuy nhiên, lần này người bệnh sẽ đi bộ trên máy thảm lăn theo một chương trình tăng dần độ khó. Bác sĩ và kỹ thuật viên sẽ liên tục theo dõi điện tâm đồ, huyết áp và nồng độ oxy máu các triệu chứng của người bệnh trong suốt quá trình gắng sức. Công dụng: Giúp bác sĩ đánh giá phản ứng của tim khi làm việc nặng từ đó có thể chẩn đoán các bệnh lý như thiếu máu cơ tim, rối loạn nhịp tim hoặc đánh giá khả năng gắng sức của người bệnh (sau nhồi máu cơ tim, sức khỏe vận động viên) và kê đơn vận động phù hợp. 
  - Gây xơ tĩnh mạch điều trị suy giãn tĩnh mạch mạn tính
    + là một phương pháp tiên tiến giúp điều trị suy giãn tĩnh mạch mạn tính, cải thiện triệu chứng và cải thiện thẩm mỹ bằng cách làm mờ hoặc loại bỏ các tĩnh mạch giãn nhìn thấy được. Người bệnh có thể vận động sớm nhẹ nhàng sau thủ thuật.
  - Tầm soát các bệnh lý tim mạch giúp phát hiện bệnh ở giai đoạn sớm nhất, tốt nhất là ngăn ngừa các nguy cơ tiềm ẩn tiến triển thành bệnh tim mạch thật sự
  - Điều trị nội khoa các bệnh lý tim mạch như: huyết áp cao, huyết áp không ổn định, suy tim, nhồi máu cơ tim, bệnh lý van tim, rối loạn nhịp tim, ...
* Nhân sự
  1. PGS.TS.BS Trương Đình Cẩm
     - Giám đốc Bệnh viện Đa khoa Hồng Đức II
     - Là chuyên gia tim mạch hàng đầu trong lĩnh vực khảo sát điện sinh lý tim, đặt máy tạo nhịp tim, nong và đặt stent động mạch vành với sang thương khó và phức tạp
  2. BSCKII. Phạm Xuân Hậu
     - Trưởng khoa Nội Tim mạch - Tim mạch can thiệp Bệnh viện Đa khoa Hồng Đức II
     - Gần 25 năm kinh nghiệm trong chuyên ngành nội khoa, nội tim mạch, can thiệp tim mạch
     - Chuyên gia trong lĩnh vực chụp động mạch vành, nong và đặt stent động mạch vành, đặt máy tạo nhịp tim tạm thời và vĩnh viễn. 
  3. BS Trần Quang Thắng
  4. BS Đặng Trịnh Cao Triệu
     - Tốt nghiệp Trường đại học Y Dược TpHCM
     - Trên 10 năm kinh nghiệm trong lĩnh vực điều trị các bệnh lý nội khoa, nội tim mạch
     - Thực hành Tim mạch can thiệp tại Bệnh viện Quân Y 175
  5. Đội ngũ điều dưỡng và kỹ thuật viên tim mạch 
     - Được đào tạo chuyên sâu về chăm sóc bệnh nhân nội tim mạch, nắm vững các kỹ thuật chuyên sâu trong tim mạch can thiệp
     - Thường xuyên học tập cập nhật kiến thức liên tục

