* Chap 2 - The Cell and Its Functions
ORGANIZATION OF THE CELL
A schematic drawing of a typical cell, as seen by the light
microscope, is shown in Fig. 2.1. Its two major parts are
the nucleus and the cytoplasm. The nucleus is separated
from the cytoplasm by a nuclear membrane, and the
cytoplasm is separated from the surrounding fluids by a
cell membrane, also called the plasma membrane.
The different substances that make up the cell are
collectively called protoplasm. Protoplasm is composed
mainly of five basic substances—water, electrolytes, proteins, lipids, and carbohydrates.
Water. Most cells, except for fat cells, are composed
mainly of water in a concentration of 70% to 85%. Many
cellular chemicals are dissolved in the water. Others are
suspended in the water as solid particulates. Chemical
reactions take place among the dissolved chemicals or at
the surfaces of the suspended particles or membranes.
Ions. Some of the important ions in the cell include
potassium, magnesium, phosphate, sulfate, bicarbonate,
and smaller quantities of sodium, chloride, and calcium.
These ions are all discussed in Chapter 4, which considers
the interrelations between the intracellular and extracellular fluids.
The ions provide inorganic chemicals for cellular reactions and are necessary for the operation of some cellular
control mechanisms. For example, ions acting at the cell
membrane are required for transmission of electrochemical impulses in nerve and muscle fibers.
Proteins. After water, the most abundant substances in
most cells are proteins, which normally constitute 10% to 20% of the cell mass. These proteins can be divided
into two main types, structural proteins and functional
proteins.
Structural proteins are present in the cell mainly in the
form of long filaments that are polymers of many individual protein molecules. A prominent use of such intracellular filaments is to form microtubules, which provide
the cytoskeletons of cellular organelles such as cilia, nerve
axons, the mitotic spindles of cells undergoing mitosis, and a tangled mass of thin filamentous tubules that
hold parts of the cytoplasm and nucleoplasm together
in their respective compartments. Fibrillar proteins are
found outside the cell, especially in the collagen and elastin fibers of connective tissue, and elsewhere, such as in
blood vessel walls, tendons, and ligaments.
The functional proteins are usually composed of combinations of a few molecules in tubular-globular form.
These proteins are mainly the enzymes of the cell and, in
contrast to the fibrillar proteins, are often mobile in the
cell fluid. Also, many of them adhere to membranous
structures inside the cell and catalyze specific intracellular chemical reactions. For example, a series of protein
enzymes catalyze the chemical reactions that split glucose
into its component parts and then combine these with
oxygen to form carbon dioxide and water while simultaneously providing energy for cellular function.
Lipids. Lipids are several types of substances grouped
together because of their common property of being soluble in fat solvents. Especially important lipids are phospholipids and cholesterol, which together constitute only about 2% of the total cell mass. Phospholipids and cholesterol are mainly insoluble in water and therefore are used
to form the cell membrane and intracellular membrane
barriers that separate the different cell compartments.
In addition to phospholipids and cholesterol, some
cells contain large quantities of triglycerides, also called
neutral fats. In fat cells (adipocytes), triglycerides often
account for as much as 95% of the cell mass. The fat stored
in these cells represents the body’s main storehouse of
energy-giving nutrients that can later be used to provide
energy wherever it is needed in the body.
Carbohydrates. Carbohydrates play a major role in cell
nutrition and, as parts of glycoprotein molecules, have
structural functions. Most human cells do not maintain
large stores of carbohydrates; the amount usually averages
only about 1% of their total mass but increases to as much
as 3% in muscle cells and, occasionally, to 6% in liver cells.
However, carbohydrate in the form of dissolved glucose
is always present in the surrounding extracellular fluid so
that it is readily available to the cell. Also, a small amount
of carbohydrate is stored in cells as glycogen, an insoluble
polymer of glucose that can be depolymerized and used
rapidly to supply the cell’s energy needs.
CELL STRUCTURE
The cell contains highly organized physical structures
called intracellular organelles, which are critical for cell
function. For example, without one of the organelles, the
mitochondria, more than 95% of the cell’s energy release
from nutrients would cease immediately. Some of the
most important organelles and other structures of the cell
are shown in Fig. 2.2.
MEMBRANOUS STRUCTURES OF THE CELL
Most organelles of the cell are covered by membranes
composed primarily of lipids and proteins. These membranes include the cell membrane surrounding the entire
cell, nuclear membrane, membrane of the endoplasmic
reticulum (ER), and membranes of the mitochondria,
lysosomes, peroxisomes, and Golgi apparatus.
The lipids in membranes provide a barrier that impedes
movement of water and water-soluble substances from
one cell compartment to another because water is not
soluble in lipids. However, protein molecules often penetrate all the way through membranes, thus providing specialized pathways, often organized into pores, for passage of specific substances through membranes. Also, many
other membrane proteins are enzymes, which catalyze a
multitude of different chemical reactions, discussed here
and in subsequent chapters.
The Cell Membrane Is a Lipid Bilayer Inserted With
Proteins. The cell membrane (also called the plasma
membrane) envelops the cell and is a thin, pliable, elastic
structure only 7.5 to 10 nanometers thick. It is composed
almost entirely of proteins and lipids. The approximate
composition is 55% proteins, 25% phospholipids, 13%
cholesterol, 4% other lipids, and 3% carbohydrates.
Fig. 2.3 shows the structure of the cell membrane.
Its basic structure is a lipid bilayer, which is a thin, double-layered film of lipids—each layer only one molecule
thick—that is continuous over the entire cell surface.
Interspersed in this lipid film are large globular proteins.
The basic lipid bilayer is composed of three main types
of lipids—phospholipids, sphingolipids, and cholesterol.
Phospholipids are the most abundant cell membrane lipids. The phosphate end of each phospholipid molecule is
hydrophilic and soluble in water. The other end is the fatty
acid portion and is hydrophobic and soluble only in fats.
Because the hydrophobic portions of the phospholipid
molecules are repelled by water but are mutually attracted
to one another, they have a natural tendency to attach to
one another in the middle of the membrane, as shown in
Fig. 2.3. The hydrophilic phosphate portions then constitute the two surfaces of the complete cell membrane,
in contact with intracellular water on the inside of the
membrane and extracellular water on the outside surface.
The lipid layer in the middle of the membrane is
impermeable to the usual water-soluble substances, such
as ions, glucose, and urea. Conversely, fat-soluble substances, such as oxygen, carbon dioxide, and alcohol, can
penetrate this portion of the membrane with ease.
Sphingolipids, derived from the amino alcohol sphingosine, also have hydrophobic and hydrophilic groups and
are present in small amounts in the cell membranes, especially nerve cells. Complex sphingolipids in cell membranes serve several functions, including protection from
harmful environmental factors, signal transmission, and
adhesion sites for extracellular proteins.
Cholesterol molecules in membranes are also lipids
because their steroid nuclei are highly fat-soluble. These
molecules, in a sense, are dissolved in the bilayer of the
membrane. They mainly help determine the degree of
permeability (or impermeability) of the bilayer to watersoluble constituents of body fluids. Cholesterol controls
much of the fluidity of the membrane as well.
Integral and Peripheral Cell Membrane Proteins.
Fig. 2.3 also shows globular masses floating in the lipid
bilayer. These membrane proteins are mainly glycoproteins. There are two types of cell membrane proteins,
integral proteins, which protrude all the way through the
membrane, and peripheral proteins, which are attached
to an integral protein or only to one surface of the membrane and do not penetrate all the way through.
Many of the integral proteins provide structural channels (or pores) through which water molecules and watersoluble substances, especially ions, can diffuse between extracellular and intracellular fluids. These protein channels also have selective properties that allow preferential
diffusion of some substances over others.
Other integral proteins act as carrier proteins for transporting substances that otherwise could not penetrate
the lipid bilayer. Sometimes, these carrier proteins even
transport substances in the direction opposite to their
electrochemical gradients for diffusion, which is called
active transport. Still others act as enzymes.
Integral membrane proteins can also serve as receptors
for water-soluble chemicals, such as peptide hormones,
that do not easily penetrate the cell membrane. Interaction of cell membrane receptors with specific ligands that
bind to the receptor causes conformational changes in
the receptor protein. This process, in turn, enzymatically
activates the intracellular part of the protein or induces
interactions between the receptor and proteins in the
cytoplasm that act as second messengers, relaying the signal from the extracellular part of the receptor to the interior of the cell. In this way, integral proteins spanning the
cell membrane provide a means of conveying information
about the environment to the cell interior.
Peripheral protein molecules are often attached to
integral proteins. These peripheral proteins function
almost entirely as enzymes or as controllers of transport
of substances through cell membrane pores.
Membrane Carbohydrates—The Cell “Glycocalyx.”
Membrane carbohydrates occur almost invariably in
combination with proteins or lipids in the form of glycoproteins or glycolipids. In fact, most of the integral
proteins are glycoproteins, and about one-tenth of the
membrane lipid molecules are glycolipids. The glyco- portions of these molecules almost invariably protrude to the
outside of the cell, dangling outward from the cell surface.
Many other carbohydrate compounds, called proteoglycans—which are mainly carbohydrates bound to small
protein cores—are loosely attached to the outer surface of
the cell as well. Thus, the entire outside surface of the cell
often has a loose carbohydrate coat called the glycocalyx.
The carbohydrate moieties attached to the outer surface of the cell have several important functions:
1. Many of them have a negative electrical charge,
which gives most cells an overall negative surface
charge that repels other negatively charged objects.
2. The glycocalyx of some cells attaches to the glycocalyx of other cells, thus attaching cells to one another.
3. Many of the carbohydrates act as receptors for binding hormones, such as insulin. When bound, this
combination activates attached internal proteins that
in turn activate a cascade of intracellular enzymes.
4. Some carbohydrate moieties enter into immune
reactions, as discussed in Chapter 35.
CYTOPLASM AND ITS ORGANELLES
The cytoplasm is filled with minute and large dispersed
particles and organelles. The jelly-like fluid portion of the
cytoplasm in which the particles are dispersed is called
cytosol and contains dissolved proteins, electrolytes, glucose, and other substances.
Dispersed in the cytoplasm are neutral fat globules,
glycogen granules, ribosomes, secretory vesicles, and five
especially important organelles—the ER, the Golgi apparatus, mitochondria, lysosomes, and peroxisomes.
Endoplasmic Reticulum
Fig. 2.2 shows the ER, a network of tubular structures called cisternae and flat vesicular structures in
the cytoplasm. This organelle helps process molecules
made by the cell and transports them for their specific
uses inside or outside the cell. The tubules and vesicles
interconnect. Also, their walls are constructed of lipid
bilayer membranes that contain large amounts of proteins, similar to the cell membrane. The total surface
area of this structure in some cells—the liver cells, for
example—can be as much as 30 to 40 times the cell
membrane area.
The detailed structure of a small portion of ER is shown
in Fig. 2.4. The space inside the tubules and vesicles, usually referred to as the cisternal space, is filled with endoplasmic matrix, a watery medium that is different from
fluid in the cytosol outside the ER. The space inside the ER
is connected with the space between the two membrane
surfaces of the nuclear membrane, providing a pipeline
between the nucleus and the cytoplasm.
Substances formed in some parts of the cell enter the
space of the ER and are then directed to other parts of the
cell. Also, the vast surface area of the ER and the multiple enzyme systems attached to its membranes provide the
mechanisms for a major share of the cell’s metabolic
functions.
Ribosomes and the Rough (Granular) Endoplasmic
Reticulum. Attached to the outer surfaces of many parts
of the ER are large numbers of minute granular particles
called ribosomes. Where these particles are present, the
reticulum is called the rough (granular) ER. The ribosomes are composed of a mixture of RNA and proteins;
they function to synthesize new protein molecules in the
cell, as discussed later in this chapter and in Chapter 3.
As shown in Fig. 2.4, the rough ER is directly continuous with the nuclear membrane. This close association
enables the ER and the nucleus to efficiently exchange
information. For example, if ER function is impaired
and proteins that are not completely processed begin to
accumulate within the organelle, the ER sends a signal to
the nucleus, which then slows ribosomal translation via
a multistep process. This gives the ER additional time to
catch up on its processing of proteins and helps maintain
cellular health.
Smooth (Agranular) Endoplasmic Reticulum. Part of
the ER has no attached ribosomes. This part is called the
smooth, or agranular, ER, which is less extensive than the
rough ER. The smooth ER functions for the synthesis of
lipid substances, detoxification of drugs and poisons, and
other processes of the cells promoted by intrareticular
enzymes.
Golgi Apparatus
The Golgi apparatus, shown in Fig. 2.5, is closely related
to the ER. It has membranes similar to those of the smooth
ER. The Golgi apparatus is usually composed of four or
more stacked layers of thin, flat, enclosed vesicles lying
near one side of the nucleus. This apparatus is prominent
in secretory cells, where it is located on the side of the cell
from which secretory substances are extruded.
The Golgi apparatus functions in association with the
ER. As shown in Fig. 2.5, small transport vesicles (also
called ER vesicles) continually pinch off from the ER and
shortly thereafter fuse with the Golgi apparatus. In this
way, substances entrapped in ER vesicles are transported
from the ER to the Golgi apparatus, which prepares them
for export outside of the cell or for transport to other
locations in the cell. Some of these substances processed
in the Golgi apparatus are used to form lysosomes, secretory vesicles, and other cytoplasmic components (discussed later in this chapter).
Lysosomes
Lysosomes, shown in Fig. 2.2 and Fig. 2.6, are vesicular
organelles that form by budding off from the membrane
of the Golgi apparatus; they then disperse throughout the
cytoplasm. The lysosomes provide an intracellular digestive system that allows the cell to digest the following: (1)
damaged cellular structures; (2) food particles that have
been ingested by the cell; and (3) unwanted matter such
as bacteria and viruses.
Lysosomes are found in all cells but are more numerous in disease-fighting cells, such as white blood cells,
that must digest greater amounts of material from bacteria and viruses. Lysosomes are usually 250 to 750 nanometers in diameter. They are surrounded by typical lipid
bilayer membranes and are filled with large numbers of
small granules, 5 to 8 nanometers in diameter, which are
protein aggregates of as many as 40 different hydrolase
(digestive) enzymes. A hydrolytic enzyme can split an
organic compound into two or more parts by combining hydrogen from a water molecule with one part of the
compound and combining the hydroxyl portion of the
water molecule with the other part of the compound. For
example, protein is hydrolyzed to form amino acids, glycogen is hydrolyzed to form glucose, and lipids are hydrolyzed to form fatty acids and glycerol.
Hydrolytic enzymes are highly concentrated in lysosomes. Ordinarily, the membrane surrounding the lysosome prevents the enclosed hydrolytic enzymes from
coming into contact with other substances in the cell and
therefore prevents their digestive actions. The cell is also
protected from exposure to the lysosome’s hydrolytic
enzymes by their dependency on an acidic environment
for activity. The lysosomal matrix, with a pH of about 4.8,
is favorable for enzymatic activity, but the cytosol’s neutral
pH renders most of the digestive enzymes inactive. However, some conditions of the cell break the membranes
of lysosomes, allowing release of the digestive enzymes.
These enzymes then split the organic substances with
which they come in contact into small, highly diffusible
substances such as amino acids and glucose. Some of the
specific functions of lysosomes are discussed later in this
chapter.
Lysosome enzyme disorders that impair cellular digestion can cause several human diseases. For example, TaySachs disease is a rare genetic disorder caused by mutation of the gene for a lysosomal enzyme (hexosaminidase A)
that breaks down complex lipids called gangliosides in the
brain and nerve cells. Excessive accumulation of these lipids damages the nervous system, causing cognitive deficits, impaired motor skills, and often premature death. In
the infantile form of Tay-Sachs disease, characterized by
almost complete lack of hexosaminidase A enzyme activity, symptoms usually start when a child is 3 to 6 months
old, and the condition may be fatal by around 3 to 5 years
of age. When there is some residual enzyme activity,
symptoms of the disease develop later in life.
Peroxisomes
Peroxisomes (Fig. 2.6) are physically similar to lysosomes,
but are different in two important ways. First, they are
formed mainly by self-replication, or perhaps also by budding off from the smooth ER rather than from the Golgi
apparatus. Peroxisomes do not have their own internal
DNA for self-replication and must import proteins from
the surrounding cytosol to make copies of themselves.
Second, they contain oxidases rather than hydrolases.
Several of the oxidases combine oxygen with hydrogen
ions derived from different intracellular chemicals to
form hydrogen peroxide (H2O2). Hydrogen peroxide is a
highly oxidizing substance and is used in association with
catalase, another oxidase enzyme present in large quantities in peroxisomes, to oxidize many substances that
might otherwise be poisonous to the cell. For example,
about half the alcohol that a person drinks is detoxified
into acetaldehyde by the peroxisomes of the liver cells in
this manner. A major function of peroxisomes is to catabolize long-chain fatty acids.
Approximately one in every 20,000 people has some
type of a peroxisomal disorder caused by molecular
defects of a single peroxisomal enzyme or that impair
peroxisome development and cause defects of several
proteins. For example, Zellweger syndrome is associated
with a decreased number of cell peroxisomes and leads to
severe disorders of the nervous system and metabolism.
Zellweger syndrome is present at birth, has no effective
treatment, and is usually fatal in the first year of life.
Secretory Vesicles
One of the important functions of many cells is secretion
of special chemical substances. Almost all such secretory
substances are formed by the ER–Golgi apparatus system
and are then released from the Golgi apparatus into the
cytoplasm in the form of storage vesicles called secretory vesicles or secretory granules. Fig. 2.7 shows typical
secretory vesicles inside pancreatic acinar cells; these vesicles store protein proenzymes (enzymes that are not yet
activated). The proenzymes are secreted later through the
outer cell membrane into the pancreatic duct and then
into the duodenum, where they become activated and
perform digestive functions on the food in the intestinal
tract.
Mitochondria
The mitochondria, shown in Fig. 2.2 and Fig. 2.8, are
the powerhouses of the cell. Without them, cells would be
unable to extract enough energy from the nutrients, and
essentially all cellular functions would cease. Mitochondria are present in all areas of each cell’s cytoplasm, but the total number per cell varies from less than
100 up to several thousand, depending on the cell’s energy
requirements. Cardiac muscle cells (cardiomyocytes), for
example, use large amounts of energy and have far more
mitochondria than fat cells (adipocytes), which use much
less energy. Furthermore, mitochondria are concentrated
in portions of the cell responsible for most of its energy
metabolism. Mitochondria are also variable in size and
shape. Some mitochondria are only a few hundred nanometers in diameter and are globular in shape, whereas
others are elongated and are as large as 1 micrometer in
diameter and 10 micrometers long.
The basic structure of a mitochondrion, shown in
Fig. 2.8, is composed mainly of two lipid bilayer-protein
membranes, an outer membrane and an inner membrane. The outer membrane contains channel proteins
(porins) that regulate the flow of ions and metabolites
across the membrane. The inner membrane has many
infoldings that form shelves or tubules called cristae onto
which oxidative enzymes are attached. The cristae provide a large surface area for chemical reactions to occur.
In addition, the inner cavity of the mitochondrion is filled
with a matrix that contains large quantities of dissolved
enzymes necessary for extracting energy from nutrients.
These enzymes operate in association with oxidative
enzymes on the cristae to cause oxidation of nutrients,
thereby forming carbon dioxide and water and, at the
same time, releasing energy. The liberated energy is used
to synthesize a high-energy substance called adenosine
triphosphate (ATP). ATP is then transported out of the
mitochondrion and diffuses throughout the cell to release
its own energy wherever it is needed for performing cellular functions. The chemical details of ATP formation by
the mitochondrion are provided in Chapter 68, but some
basic functions of ATP in the cell are introduced later in
this chapter.
Mitochondria are self-replicative, which means that
one mitochondrion can form a second one, a third one,
and so on whenever the cell needs increased amounts
of ATP. Indeed, the mitochondria contain DNA. In
Chapter 3, we will see that DNA is the basic constituent of
the nucleus that controls replication of the cell. The DNA
of the mitochondrion plays a similar role, controlling
replication of the mitochondrion. Mitochondrial DNA is
localized to the matrix, which also contains enzymes and
ribosomes for protein synthesis. Cells that are faced with
increased energy demands—for example, in skeletal muscles subjected to chronic exercise training—may increase
the density of mitochondria to supply the additional
energy required.
Mitochondrial DNA (mtDNA) contains 37 genes that
are essential for mitochondrial function and is primarily
inherited from the mother, although some evidence suggests that in rare instances mtDNA may also be inherited
from the father. Mitochondria of sperm are usually carried in the tail, which drops off when the sperm attaches
to the egg during fertilization. Thus, the only mtDNA the
new organism usually receives is from its mother’s egg.
This means that mtDNA, unlike nuclear DNA which
comes from both parents, does not get reordered every
generation.
Mutations of mtDNA can occur, leading to inherited
mitochondrial disorders that impair energy production. In diseases caused by mtDNA mutations, normal
and mutant mtDNA molecules typically coexist in cells,
a condition termed heteroplasmy. The severity of mitochondrial diseases caused by genetic changes in mtDNA
is partly determined by the amount of mutant mtDNA
in the cells, which, in turn, is dictated by the number of
copies of mutant mtDNA in the mother’s fertilized egg.
However, mitochondrial diseases can also be caused by
mutations of approximately 1300 nuclear genes that
encode proteins that regulate mitochondrial function.
There is considerable heterogeneity of mitochondrial diseases, with onset occurring from early childhood to adulthood, depending on the specific cause.
Cell Cytoskeleton—Filament and Tubular
Structures
The cell cytoskeleton is a network of fibrillar proteins
organized into filaments or tubules. These originate as
precursor proteins synthesized by ribosomes in the cytoplasm. The precursor molecules then polymerize to form
filaments (Fig. 2.9). As an example, large numbers of
actin microfilaments frequently occur in the outer zone
of the cytoplasm, called the ectoplasm, to form an elastic support for the cell membrane. Also, in muscle cells,
actin and myosin filaments are organized into a special
contractile machine that is the basis for muscle contraction, as discussed in Chapter 6.
Intermediate filaments are generally strong ropelike
filaments that often work together with microtubules,
providing strength and support for the fragile tubulin structures. They are called intermediate because their
average diameter is between that of narrower actin microfilaments and wider myosin filaments found in muscle
cells. Their functions are mainly mechanical, and they are
less dynamic than actin microfilaments or microtubules.
All cells have intermediate filaments, although the protein subunits of these structures vary, depending on the
cell type. Specific intermediate filaments found in various
cells include desmin filaments in muscle cells, neurofilaments in neurons, and keratins in epithelial cells.
A special type of stiff filament composed of polymerized tubulin molecules is used in all cells to construct
strong tubular structures, the microtubules. Fig. 2.9
shows typical microtubules of a cell.
Another example of microtubules is the tubular skeletal
structure in the center of each cilium that radiates upward
from the cell cytoplasm to the tip of the cilium. This structure is discussed later in the chapter (see Fig. 2.18). Also,
both the centrioles and mitotic spindles of cells undergoing mitosis are composed of stiff microtubules.
A major function of microtubules is to act as a cytoskeleton, providing rigid physical structures for certain parts
of cells. The cell cytoskeleton not only determines cell
shape but also participates in cell division, allows cells to
move, and provides a tracklike system that directs movement of organelles in the cells. Microtubules serve as the
conveyor belts for the intracellular transport of vesicles,
granules, and organelles such as mitochondria.
Nucleus
The nucleus is the control center of the cell and sends
messages to the cell to grow and mature, replicate, or
die. Briefly, the nucleus contains large quantities of DNA,
which comprise the genes. The genes determine the
characteristics of the cell’s proteins, including structural
proteins and the intracellular enzymes that control cytoplasmic and nuclear activities.
The genes also control and promote cell reproduction.
The genes first reproduce to create two identical sets of
genes; then the cell splits by a special process called mitosis to form two daughter cells, each of which receives one
of the two sets of DNA genes. All these activities of the
nucleus are discussed in Chapter 3.
Fig. 2.10 illustrates the appearance of the nucleus
during interphase (the period between mitoses), revealing darkly staining chromatin material throughout the
nucleoplasm. During mitosis, the chromatin material
organizes in the form of highly structured chromosomes,
which can be easily identified using the light microscope,
as illustrated in Chapter 3.
Nuclear Membrane. The nuclear membrane, also called
the nuclear envelope, is actually two separate bilayer membranes, one inside the other. The outer membrane is continuous with the ER of the cell cytoplasm, and the space
between the two nuclear membranes is also continuous
with the space inside the ER, as shown in Figs. 2.4 and 2.10. The nuclear membrane is penetrated by several thousand nuclear pores. Large complexes of proteins are
attached at the edges of the pores so that the central area
of each pore is only about 9 nanometers in diameter, permitting molecules up to a molecular weight of 44,000 to
pass through with reasonable ease. Even larger molecules
can cross nuclear pore complexes through selective,
receptor-mediated transport.
Nucleoli and Formation of Ribosomes. The nuclei of
most cells contain one or more highly staining structures
called nucleoli. The nucleolus, unlike most other organelles discussed here, does not have a limiting membrane.
Instead, it is simply an accumulation of large amounts of
RNA and the types of proteins found in ribosomes. The
nucleolus enlarges considerably when the cell is actively
synthesizing proteins.
Formation of the nucleoli (and of the ribosomes in
the cytoplasm outside the nucleus) begins in the nucleus.
First, specific DNA genes in the chromosomes cause
RNA to be synthesized. Some of this synthesized RNA is
stored in the nucleoli, but most of it is transported outward through the nuclear pores into the cytoplasm. Here
it is used in conjunction with specific proteins to assemble
“mature” ribosomes that play an essential role in forming
cytoplasmic proteins, as discussed in Chapter 3 
FUNCTIONAL SYSTEMS OF THE CELL
Although the cells of different tissues and organs of the
human body are highly specialized, they share many common functions. In the remainder of this chapter, we discuss some functional systems of the cell that make it a
living organism.
ENDOCYTOSIS—INGESTION BY THE CELL
For cells to live, grow and reproduce, they must obtain
nutrients and other substances from the surrounding fluids. Most substances pass through the cell membrane by
the processes of diffusion and active transport.
Diffusion involves simple movement through the membrane caused by the random motion of the molecules of
the substance. Substances move through cell membrane
pores or, in the case of lipid-soluble substances, through
the lipid matrix of the membrane.
Active transport involves actually carrying a substance
through the membrane by a physical protein structure
that penetrates all the way through the membrane. These
active transport mechanisms are so important to cell
function that they are presented in detail in Chapter 4.
Large particles enter the cell by a specialized function of the cell membrane called endocytosis (Video 2.1).
The principal forms of endocytosis are pinocytosis and
phagocytosis. Pinocytosis means the ingestion of minute
particles that form vesicles of extracellular fluid and particulate constituents inside the cell cytoplasm. Phagocytosis means the ingestion of large particles, such as bacteria,
whole cells, or portions of degenerating tissue.
Pinocytosis. Pinocytosis occurs continually in the cell
membranes of most cells, but is especially rapid in some
cells. For example, it occurs so rapidly in macrophages
that about 3% of the total macrophage membrane is
engulfed in the form of vesicles each minute. Even so, the
pinocytotic vesicles are so small—usually only 100 to 200
nanometers in diameter—that most of them can be seen
only with an electron microscope.
Pinocytosis is a means whereby most large macromolecules, such as most proteins, can enter cells. In fact, the
rate at which pinocytotic vesicles form is usually enhanced
when such macromolecules attach to the cell membrane.
Fig. 2.11A–D demonstrates the successive steps of
pinocytosis, showing three molecules of protein attaching to the membrane. These molecules usually attach to
specialized protein receptors on the surface of the membrane that are specific for the type of protein that is to
be absorbed. The receptors generally are concentrated
in small pits on the outer surface of the cell membrane,
called coated pits. On the inside of the cell membrane
beneath these pits is a latticework of fibrillar protein called clathrin, as well as other proteins, perhaps including contractile filaments of actin and myosin. Once the
protein molecules have bound with the receptors, the
surface properties of the local membrane change in such
a way that the entire pit invaginates inward, and fibrillar
proteins surrounding the invaginating pit cause its borders to close over the attached proteins, as well as over a
small amount of extracellular fluid. Immediately thereafter, the invaginated portion of the membrane breaks away
from the surface of the cell, forming a pinocytotic vesicle
inside the cytoplasm of the cell.
This pinocytotic process requires energy from within
the cell, which is supplied by ATP, a high-energy substance discussed later in this chapter. This process also
requires the presence of calcium ions (Ca2+) in the extracellular fluid, which react with contractile protein filaments beneath the coated pits to provide the force for
pinching the vesicles away from the cell membrane.
Phagocytosis. Phagocytosis occurs in much the same
way as pinocytosis, except that it involves large particles
rather than molecules. Only certain cells have the capability of phagocytosis—notably, tissue macrophages and
some white blood cells.
Phagocytosis is initiated when a particle such as a bacterium, dead cell, or tissue debris binds with receptors on
the surface of the phagocyte. In the case of bacteria, each
bacterium is usually attached to a specific antibody, and it
is the antibody that attaches to the phagocyte receptors,
dragging the bacterium along with it. This intermediation of antibodies is called opsonization, as discussed in
Chapters 34 and 35.
Phagocytosis occurs in the following steps:
1. The cell membrane receptors attach to the surface
ligands of the particle.
2. The edges of the membrane around the points of attachment evaginate outward within a fraction of a
second to surround the entire particle; then, progressively more and more membrane receptors attach to
the particle ligands. All this occurs suddenly in a zipper-like manner to form a closed phagocytic vesicle.
3. Actin and other contractile fibrils in the cytoplasm
surround the phagocytic vesicle and contract
around its outer edge, pushing the vesicle to the interior.
4. The contractile proteins then pinch the stem of the
vesicle so completely that the vesicle separates from
the cell membrane, leaving the vesicle in the cell interior in the same way that pinocytotic vesicles are
formed.
LYSOSOMES DIGEST PINOCYTOTIC AND
PHAGOCYTIC FOREIGN SUBSTANCES
INSIDE THE CELL
Almost immediately after a pinocytotic or phagocytic vesicle appears inside a cell, one or more lysosomes become
attached to the vesicle and empty their acid hydrolases
to the inside of the vesicle, as shown in Fig. 2.12. Thus,
a digestive vesicle is formed inside the cell cytoplasm in
which the vesicular hydrolases begin hydrolyzing the proteins, carbohydrates, lipids, and other substances in the
vesicle. The products of digestion are small molecules of
substances such as amino acids, glucose, and phosphates
that can diffuse through the membrane of the vesicle into
the cytoplasm. What is left of the digestive vesicle, called
the residual body, represents indigestible substances. In
most cases, the residual body is finally excreted through
the cell membrane by a process called exocytosis, which is
essentially the opposite of endocytosis. Thus, the pinocytotic and phagocytic vesicles containing lysosomes can be
called the digestive organs of the cells.
Lysosomes and Regression of Tissues and Autolysis
of Damaged Cells. Tissues of the body often regress to
a smaller size. For example, this regression occurs in the
uterus after pregnancy, in muscles during long periods of
inactivity, and in mammary glands at the end of lactation.
Lysosomes are responsible for much of this regression.
Another special role of the lysosomes is removal of
damaged cells or damaged portions of cells from tissues.
Damage to the cell—caused by heat, cold, trauma, chemicals, or any other factor—induces lysosomes to release
hydrolases, which digest the surrounding organic substances. If the damage is slight, only a portion of the cell
is removed, and the cell is then repaired. If the damage is
severe, the entire cell is digested, a process called autolysis.
In this way, the cell is completely removed, and a new cell
of the same type is formed, ordinarily by mitotic reproduction of an adjacent cell to take the place of the old one.
The lysosomes also contain bactericidal agents that
can kill phagocytized bacteria before they cause cellular damage. These agents include the following: (1) lysozyme, which dissolves the bacterial cell wall; (2) lysoferrin,
which binds iron and other substances before they can
promote bacterial growth; and (3) acid at a pH of about 4.8, which activates the hydrolases and inactivates bacterial metabolic systems.
Autophagy and Recycling of Cell Organelles. Lysosomes play a key role in the process of autophagy, which
literally means “to eat oneself.” Autophagy is a housekeeping process whereby obsolete organelles and large protein
aggregates are degraded and recycled (Fig. 2.13). Wornout cell organelles are transferred to lysosomes by double-membrane structures called autophagosomes, which
are formed in the cytosol. Invagination of the lysosomal
membrane and the formation of vesicles provide another
pathway for cytosolic structures to be transported into
the lumen of lysosomes. Once inside the lysosomes, the
organelles are digested, and the nutrients are reused by
the cell. Autophagy contributes to the routine turnover of
cytoplasmic components; it is a key mechanism for tissue
development, cell survival when nutrients are scarce, and
homeostasis. In liver cells, for example, the average mitochondrion normally has a life span of only about 10 days
before it is destroyed.
SYNTHESIS OF CELLULAR STRUCTURES BY
ENDOPLASMIC RETICULUM AND GOLGI
APPARATUS
Endoplasmic Reticulum Functions
The extensiveness of the ER and Golgi apparatus in secretory cells has already been emphasized. These structures
are formed primarily of lipid bilayer membranes, similar
to the cell membrane, and their walls are loaded with
protein enzymes that catalyze the synthesis of many substances required by the cell.
Most synthesis begins in the ER. The products formed
there are then passed on to the Golgi apparatus, where
they are further processed before being released into the
cytoplasm. First, however, let us note the products that
are synthesized in specific portions of the ER and Golgi
apparatus.
Proteins Synthesis By the Rough Endoplasmic Reticulum. The rough ER has large numbers of ribosomes
attached to the outer surfaces of the ER membrane. As
discussed in Chapter 3, proteins are synthesized within
the structures of the ribosomes. The ribosomes extrude
some of the synthesized proteins directly into the cytosol,
but they also extrude many more through the wall of the
ER to the interior of the endoplasmic vesicles and tubules
into the endoplasmic matrix.
Lipid Synthesis By the Smooth Endoplasmic Reticulum. The ER also synthesizes lipids, especially phospholipids and cholesterol. These lipids are rapidly
incorporated into the lipid bilayer of the ER, thus causing the ER to grow more extensive. This process occurs
mainly in the smooth portion of the ER.
To keep the ER from growing beyond the cell’s needs,
small vesicles called ER vesicles or transport vesicles continually break away from the smooth reticulum; most of
these vesicles then migrate rapidly to the Golgi apparatus.
Other Functions of the Endoplasmic Reticulum. Other
significant functions of the ER, especially the smooth
reticulum, include the following:
1. It provides the enzymes that control glycogen
breakdown when glycogen is to be used for energy.
2. It provides a vast number of enzymes that are capable of detoxifying substances, such as drugs, that
might damage the cell. It achieves detoxification by
processes such as coagulation, oxidation, hydrolysis, and conjugation with glycuronic acid.
Golgi Apparatus Functions
Synthetic Functions of the Golgi Apparatus. Although
a major function of the Golgi apparatus is to provide additional processing of substances already formed in the
ER, it can also synthesize certain carbohydrates that cannot be formed in the ER. This is especially true for the
formation of large saccharide polymers bound with small
amounts of protein; important examples include hyaluronic acid and chondroitin sulfate.
A few of the many functions of hyaluronic acid and
chondroitin sulfate in the body are as follows: (1) they are
major components of proteoglycans secreted in mucus
and other glandular secretions; (2) they are major components of the ground substance, or nonfibrous components
of the extracellular matrix, outside the cells in the interstitial spaces, which serve several important functions,
including acting as fillers between collagen fibers and cells;
(3) they are principal components of the organic matrix
in both cartilage and bone; and (4) they are important in
many cell activities, including migration and proliferation.
Processing of Endoplasmic Reticulum Secretions By
the Golgi Apparatus—Formation of Vesicles. Fig. 2.14
summarizes the major functions of the ER and Golgi
apparatus. As substances are formed in the ER, especially
proteins, they are transported through the tubules toward
portions of the smooth ER that lie nearest to the Golgi
apparatus. At this point, transport vesicles composed of
small envelopes of smooth ER continually break away and
diffuse to the deepest layer of the Golgi apparatus. Inside
these vesicles are synthesized proteins and other products
from the ER.
The transport vesicles fuse with the Golgi apparatus
and empty their contained substances into the vesicular spaces of the Golgi apparatus. Here, additional carbohydrate moieties are added to the secretions. Also, an
important function of the Golgi apparatus is to compact
the ER secretions into highly concentrated packets. As
the secretions pass toward the outermost layers of the
Golgi apparatus, the compaction and processing proceed. Finally, small and large vesicles continually break
away from the Golgi apparatus, carrying with them the
compacted secretory substances and diffusing throughout the cell.
The following example provides an idea of the timing of these processes. When a glandular cell is bathed
in amino acids, newly formed protein molecules can be
detected in the granular ER within 3 to 5 minutes. Within
20 minutes, newly formed proteins are already present in
the Golgi apparatus and, within 1 to 2 hours, the proteins
are secreted from the surface of the cell.
Secretory Vesicles Are Formed By the Golgi Apparatus. In a highly secretory cell, the vesicles formed by the
Golgi apparatus are mainly secretory vesicles containing
proteins that are secreted through the surface of the cell
membrane. These secretory vesicles first diffuse to the
cell membrane and then fuse with it and empty their substances to the exterior by the mechanism called exocytosis. Exocytosis, in most cases, is stimulated by entry of
Ca2+ into the cell. Calcium ions interact with the vesicular
membrane and cause its fusion with the cell membrane,
followed by exocytosis—opening of the membrane’s outer
surface and extrusion of its contents outside the cell.
Some vesicles, however, are destined for intracellular use.
Use of Intracellular Vesicles to Replenish Cellular
Membranes. Some intracellular vesicles formed by the
Golgi apparatus fuse with the cell membrane or with
the membranes of intracellular structures such as the
mitochondria and even the ER. This fusion increases the
expanse of these membranes and replenishes the membranes as they are used. For example, the cell membrane
loses much of its substance every time it forms a phagocytic or pinocytotic vesicle, and the vesicular membranes
of the Golgi apparatus continually replenish the cell
membrane.
In summary, the membranous system of the ER and
Golgi apparatus is highly metabolic and capable of forming new intracellular structures and secretory substances
to be extruded from the cell.
MITOCHONDRIA EXTRACT ENERGY FROM
NUTRIENTS
The principal substances from which cells extract energy
are foods that react chemically with oxygen—carbohydrates, fats, and proteins. In the human body, essentially all carbohydrates are converted into glucose by the
digestive tract and liver before they reach the other cells
of the body. Similarly, proteins are converted into amino
acids, and fats are converted into fatty acids. Fig. 2.15
shows oxygen and the foodstuffs—glucose, fatty acids,
and amino acids—all entering the cell. Inside the cell,
they react chemically with oxygen under the influence
of enzymes that control the reactions and channel the
energy released in the proper direction. The details of all these digestive and metabolic functions are provided in
Chapters 63 through 73.
Briefly, almost all these oxidative reactions occur
inside the mitochondria, and the energy that is released
is used to form the high-energy compound ATP. Then,
ATP, not the original food, is used throughout the cell to
energize almost all the subsequent intracellular metabolic
reactions.
Functional Characteristics of Adenosine
Triphosphate ATP is a nucleotide composed of the following: (1) the
nitrogenous base adenine; (2) the pentose sugar ribose;
and (3) three phosphate radicals. The last two phosphate
radicals are connected with the remainder of the molecule
by high-energy phosphate bonds, which are represented in
the formula shown by the symbol ∼. Under the physical
and chemical conditions of the body, each of these highenergy bonds contains about 12,000 calories of energy per
mole of ATP, which is many times greater than the energy
stored in the average chemical bond, thus giving rise to
the term high-energy bond. Furthermore, the high-energy
phosphate bond is very labile and can be split instantly on
demand whenever energy is required to promote other
intracellular reactions.
When ATP releases its energy, a phosphoric acid radical is split away, and adenosine diphosphate (ADP) is
formed. This released energy is used to energize many of
the cell’s other functions, such as syntheses of substances
and muscular contraction.
To reconstitute the cellular ATP as it is used, energy
derived from the cellular nutrients causes ADP and phosphoric acid to recombine to form new ATP, and the entire
process is repeated over and over. For these reasons, ATP
has been called the energy currency of the cell because it
can be spent and reformed continually, having a turnover
time of only a few minutes.
Role of Mitochondria in Forming ATP. On entry into the
cells, glucose is converted by enzymes in the cytoplasm into
pyruvic acid (a process called glycolysis). A small amount
of ADP is changed into ATP by the energy released during
this conversion, but this amount accounts for less than 5%
of the overall energy metabolism of the cell.
About 95% of the cell’s ATP formation occurs in the
mitochondria. Pyruvic acid derived from carbohydrates,
fatty acids from lipids, and amino acids from proteins are
eventually converted into the compound acetyl-coenzyme A (CoA) in the matrix of mitochondria. This substance, in turn, is further dissolved to extract its energy
by another series of enzymes in the mitochondrion
matrix, undergoing a sequence of chemical reactions
called the citric acid cycle, or Krebs cycle. These chemical reactions are so important that they are explained in
detail in Chapter 68.
In this citric acid cycle, acetyl-CoA is split into its
component parts, hydrogen atoms and carbon dioxide.
The carbon dioxide diffuses out of the mitochondria and
the cell; finally, it is excreted from the body through the
lungs. The hydrogen atoms, however, are highly reactive
and combine with oxygen that has also diffused into the
mitochondria. This combination releases a tremendous
amount of energy, which is used by mitochondria to convert large amounts of ADP to ATP.
The processes of these reactions are complex, requiring
participation of many protein enzymes that are integral
parts of mitochondrial membranous shelves that protrude into the mitochondrial matrix. The initial event is
the removal of an electron from the hydrogen atom, thus
converting it to a hydrogen ion. The terminal event is the
combination of hydrogen ions with oxygen to form water
and the release of large amounts of energy to globular
proteins called ATP synthetase that protrude like knobs
from the membranes of the mitochondrial shelves. The
enzyme ATP synthetase then uses the energy from the
hydrogen ions to convert ADP to ATP. The newly formed
ATP is transported out of the mitochondria into all parts
of the cell cytoplasm and nucleoplasm, where it energizes
multiple cell functions. This overall process for formation of ATP is called the
chemiosmotic mechanism of ATP formation. The chemical and physical details of this mechanism are presented
in Chapter 68, and many of the detailed metabolic functions of ATP in the body are discussed in Chapters 68
through 72.
Uses of ATP for Cellular Function. Energy from ATP
is used to promote three major categories of cellular
functions: (1) transport of substances through multiple
cell membranes; (2) synthesis of chemical compounds
throughout the cell; and (3) mechanical work. These uses
of ATP are illustrated by the examples in Fig. 2.16: (1) to
supply energy for sodium transport through the cell membrane; (2) to promote protein synthesis by the ribosomes;
and (3) to supply energy needed for muscle contraction.
In addition to membrane transport of sodium, energy
from ATP is required for membrane transport of potassium, calcium, magnesium, phosphate, chloride, urate,
and hydrogen ions and many other ions, as well as various
organic substances. Membrane transport is so important
to cell function that some cells—the renal tubular cells,
for example—use as much as 80% of the ATP that they
form for this purpose alone.
In addition to synthesizing proteins, cells make phospholipids, cholesterol, purines, pyrimidines, and many
other substances. Synthesis of almost any chemical compound requires energy. For example, a single protein molecule might be composed of as many as several thousand
amino acids attached to one another by peptide linkages.
The formation of each of these linkages requires energy
derived from the breakdown of four high-energy bonds;
thus, many thousand ATP molecules must release their
energy as each protein molecule is formed. Indeed, some
cells use as much as 75% of all the ATP formed in the cell
simply to synthesize new chemical compounds, especially
proteins during the growth phase of cells.
Another use of ATP is to supply energy for special cells
to perform mechanical work. We discuss in Chapter 6
that each contraction of a muscle fiber requires expenditure of large quantities of ATP energy. Other cells perform mechanical work in different ways, especially by
ciliary and ameboid motion, described later in this chapter. The source of energy for all these types of mechanical
work is ATP.
In summary, ATP is readily available to release its
energy rapidly wherever it is needed in the cell. To replace
ATP used by the cell, much slower chemical reactions
break down carbohydrates, fats, and proteins and use the
energy derived from these processes to form new ATP.
More than 95% of this ATP is formed in the mitochondria, which is why the mitochondria are called the powerhouses of the cell. 
LOCOMOTION OF CELLS
The most obvious types of movement in the body occur
in skeletal, cardiac, and smooth muscle cells, which constitute almost 50% of the entire body mass. The specialized functions of these cells are discussed in Chapters 6
through 9. Two other types of movement—ameboid locomotion and ciliary movement—occur in other cells.
Ameboid Movement
Ameboid movement is a crawling-like movement of an
entire cell, such as movement of white blood cells through
tissues. This type of movement gets its name from the fact
that amebae move in this manner, and amebae have provided an excellent tool for studying the phenomenon.
Typically, ameboid locomotion begins with the protrusion of a pseudopodium from one end of the cell. The
pseudopodium projects away from the cell body and partially secures itself in a new tissue area; then the remainder
of the cell is pulled toward the pseudopodium. Fig. 2.17
demonstrates this process, showing an elongated cell, the
right-hand end of which is a protruding pseudopodium. The membrane of this end of the cell is continually moving forward, and the membrane at the left-hand end of the
cell is continually following along as the cell moves.
Mechanism of Ameboid Locomotion. Fig. 2.17 shows
the general principle of ameboid motion. Basically, this
results from the continual formation of new cell membrane at the leading edge of the pseudopodium and continual absorption of the membrane in the mid and rear
portions of the cell. Two other effects are also essential
for forward movement of the cell. The first is attachment
of the pseudopodium to surrounding tissues so that it
becomes fixed in its leading position while the remainder
of the cell body is being pulled forward toward the point
of attachment. This attachment is caused by receptor proteins that line the insides of exocytotic vesicles. When
the vesicles become part of the pseudopodial membrane,
they open so that their insides evert to the outside, and
the receptors now protrude to the outside and attach to
ligands in the surrounding tissues.
At the opposite end of the cell, the receptors pull away
from their ligands and form new endocytotic vesicles.
Then, inside the cell, these vesicles stream toward the
pseudopodial end of the cell, where they are used to form
new membrane for the pseudopodium.
The second essential requirement for locomotion is the
energy to pull the cell body in the direction of the pseudopodium. A moderate to large amount of the protein actin
is in the cytoplasm of all cells. Much of the actin is in the
form of single molecules that do not provide any motive
power; however, these molecules polymerize to form a
filamentous network, and the network contracts when it
binds with an actin-binding protein such as myosin. The
entire process is energized by the high-energy compound
ATP. This is what occurs in the pseudopodium of a moving cell, where such a network of actin filaments forms
anew inside the enlarging pseudopodium. Contraction
also occurs in the ectoplasm of the cell body, where a preexisting actin network is already present beneath the cell
membrane.
Cells That Exhibit Ameboid Locomotion. The most
common cells to exhibit ameboid locomotion in the
human body are the white blood cells when they move
out of the blood into the tissues to form tissue macrophages. Other types of cells can also move by ameboid
locomotion under certain circumstances. For example,
fibroblasts move into a damaged area of tissues to help
repair the damage. Even the germinal cells of the skin,
although ordinarily completely sessile cells, move toward
a cut area to repair the opening. Cell locomotion is also
especially important in development of the embryo and
fetus after fertilization of an ovum. For example, embryonic cells often must migrate long distances from their
sites of origin to new areas during the development of
special structures.
Some types of cancer cells, such as sarcomas, which
arise from connective tissue cells, are especially proficient
at ameboid movement. This partially explains their
relatively rapid spreading from one part of the body to
another, known as metastasis.
Control of Ameboid Locomotion—Chemotaxis. An
important initiator of ameboid locomotion is the process
called chemotaxis, which results from the appearance of
certain chemotactic substances in the tissues. Most cells
that exhibit ameboid locomotion move toward the source
of a chemotactic substance—that is, from an area of lower
concentration toward an area of higher concentration.
This is called positive chemotaxis. Some cells move away
from the source, which is called negative chemotaxis.
The side of the cell most exposed to the chemotactic substance develops membrane changes that cause pseudopodial protrusion.
Cilia and Ciliary Movements
There are two types of cilia, motile and nonmotile (primary) cilia. Motile cilia can undergo a whiplike movement on the surfaces of cells. This movement occurs
mainly in two places in the human body, on the surfaces
of the respiratory airways and on the inside surfaces of the
uterine tubes (fallopian tubes) of the reproductive tract.
In the nasal cavity and lower respiratory airways, the
whiplike motion of motile cilia causes a layer of mucus to
move at a rate of about 1 cm/min toward the pharynx, in
this way continually clearing these passageways of mucus
and particles that become trapped in the mucus. In the
uterine tubes, cilia cause slow movement of fluid from the
ostium of the uterine tube toward the uterus cavity; this
movement of fluid transports the ovum from the ovary to
the uterus.
Fig. 2.18 shows a cilium with the appearance of a
sharp-pointed straight or curved hair that projects 2 to
4 micrometers from the surface of the cell. Often, many
motile cilia project from a single cell—for example, as
many as 200 cilia on the surface of each epithelial cell
inside the respiratory passageways. The cilium is covered
by an outcropping of the cell membrane, and it is supported by 11 microtubules—nine double tubules located
around the periphery of the cilium and two single tubules
down the center, as demonstrated in the cross section
shown in Fig. 2.18. Each cilium is an outgrowth of a
structure that lies immediately beneath the cell membrane, called the basal body of the cilium.
The flagellum of a sperm is similar to a motile cilium;
in fact, it has much the same type of structure and same
type of contractile mechanism. The flagellum, however, is
much longer and moves in quasi sinusoidal waves instead
of whiplike movements.
In the inset of Fig. 2.18, movement of the motile cilium is shown. The cilium moves forward with a sudden,
rapid whiplike stroke 10 to 20 times per second, bending
sharply where it projects from the surface of the cell. Then
it moves backward slowly to its initial position. The rapid,
forward-thrusting, whiplike movement pushes the fluid lying adjacent to the cell in the direction that the cilium
moves; the slow dragging movement in the backward
direction has almost no effect on fluid movement. As a
result, the fluid is continually propelled in the direction of
the fast-forward stroke. Because most motile ciliated cells
have large numbers of cilia on their surfaces, and because
all the cilia are oriented in the same direction, this is an
effective means for moving fluids from one part of the
surface to another.
Mechanism of Ciliary Movement. The nine double
tubules and two single tubules of cilia are all linked to
one another by a complex of protein cross-linkages; this
total complex of tubules and cross-linkages is called
the axoneme. Even after removal of the membrane and
destruction of other elements of the cilium in addition to
the axoneme, the cilium can still beat under appropriate
conditions. Two conditions are necessary for continued
beating of the axoneme after removal of the other structures of the cilium: (1) the availability of ATP; and (2)
appropriate ionic conditions, especially appropriate concentrations of magnesium and calcium. During forward
motion of the cilium, the double tubules on the front
edge of the cilium slide outward toward the tip of the
cilium, whereas those on the back edge remain in place.
Multiple protein arms composed of the protein dynein,
which has adenosine triphosphatase (ATPase) enzymatic
activity, project from each double tubule toward an adjacent double tubule.
Given this basic information, it has been determined
that the release of energy from ATP in contact with the
ATPase dynein arms causes the heads of these arms to
“crawl” rapidly along the surface of the adjacent double
tubule. If the front tubules crawl outward while the back
tubules remain stationary, bending occurs.
The cilia of some genetically abnormal cells do not
have the two central single tubules, and these cilia fail to
beat. Therefore, it is presumed that some signal, perhaps
an electrochemical signal, is transmitted along these two
central tubules to activate the dynein arms.
Nonmotile Primary Cilia Serve as Cell Sensory “Antennae.” Primary cilia are nonmotile and generally occur
only as a single cilium on each cell. Current evidence
indicates that they function as cellular “sensory antennae,”
which coordinate cellular signaling pathways involved in
chemical and mechanical sensation, signal transduction,
and cell growth. In the kidneys, for example, primary cilia
are found in most epithelial cells of the tubules, projecting into the tubule lumen and acting as a flow sensor. In
response to fluid flow over the tubular epithelial cells, the
primary cilia bend and cause flow-induced changes in
intracellular calcium signaling. These signals, in turn, initiate multiple effects on the cells. Defects in signaling by
primary cilia in renal tubular epithelial cells are thought
to contribute to various disorders, including the development of large fluid-filled cysts, a condition called polycystic kidney disease. 
