* Tóm tắt quá trình bệnh
- Bệnh nhân nam, 55 tuổi, nhập viện vì mệt, đau bụng, nôn ói và tiêu lỏng
- Bệnh nhân có tiền căn tăng huyết áp chưa điều trị, HIV đang điều trị với thuốc ARV
- Trước nhập viện 01 ngày, sau khi bệnh nhân ăn cơm tại quán ăn thì xuất hiện triệu chứng đau bụng quanh rốn kèm buồn nôn, nôn ói, tiêu phân lỏng. Bệnh nhân tự mua thuốc uống nhưng đến hôm sau vẫn còn đau bụng, buồn nôn, nôn, mệt nhiều hơn nên đến khám và nhập viện tại Bệnh viện Hồng Đức II. Bệnh nhân được thăm khám và thực hiện các cận lâm sàng, chẩn đoán: Nhiễm trùng đường ruột, Tổn thương thận cấp, Tăng huyết áp/ HIV đang điều trị thuốc ARV. Bệnh được điều trị kháng sinh, bồi hoàn nước - điện giải, ổn định huyết áp, điều trị triệu chứng. Sau 4 ngày điều trị bệnh nhân khỏe dần, hết các triệu chứng đau bụng, buồn nôn - nôn, tiêu lỏng, huyết áp ổn định, xét nghiệm máu chức năng thận cải thiện dần. Bệnh nhân được xuất viện và theo dõi tiếp tục tại phòng khám. 
* Thông điệp
- Nhiễm trùng đường ruột do thức ăn rất thường gặp. Các triệu chứng có thể từ nhẹ, trung bình đến nặng. Một số có thể tự khỏi như một rối loạn tiêu hóa thông thường, một số có thể diễn tiến rất nặng nếu người bệnh không được điều trị đúng đắn, đặc biệt là những bệnh nhân có nhiều bệnh nền, có cơ địa suy giảm miễn dịch như người già, người mắc bệnh đái tháo đường, bệnh thận mạn, người nhiễm HIV, ...; triệu chứng ban đầu trên những người bệnh này có thể không rầm rộ như người khỏe mạnh nên có thể chủ quan, điều trị muộn dẫn đến biến chứng rất nặng như nhiễm trùng huyết, suy đa cơ quan, tử vong. 
- Lời khuyên: Đảm bảo vệ sinh an toàn thực phẩm là rất quan trọng. Người bệnh không nên chủ quan, tự điều trị đặc biệt là người có nhiều bệnh nền, suy giảm miễn dịch, nên đến gặp bác sĩ để được thăm khám điều trị đúng đắn và kịp thời. 