* 03/01/2026
** Memories, Dreams, Relfections
  - For all: Despite
  - above all: most important, trên hết
  - Inception: khởi đầu
  - Conception: quan niệm/khái niệm. Thụ thai, inception of motherhood
  - It is not for me to do st: not allowed to do st
  - Fend off other obligations: Gác lại hoặc đẩy lùi các nghĩa vụ/công việc khác
  - Take the plunge: Một thành ngữ có nghĩa là quyết tâm thực hiện một việc gì đó quan trọng hoặc khó khăn sau khi đã đắn đo (quyết tâm "đâm lao").
  - In vain: Vô ích, vô vọng, không đem lại kết quả gì. I asked in vain. 
  - take (st) for granted: lẽ đương nhiên, hiển nhiên, không trân trọng
  - "Never felt any disposition to" means someone lacks the natural inclination, mood, or desire (disposition) to do something, often implying a lack of feeling, interest, or readiness, like "never felt any disposition to argue" (no desire to) or "never felt any disposition to complain" (never felt like it)
  - inexplicable: không giải thích được
* 04/01/2026
** Memories, Dreams, Relfections
  - Pretense (n): sự giả vờ
  - At most: cùng lắm, tối đa
  - dubious: mơ hồ
  - fleeting (adj): thoáng qua
* 06/01/2026
** Memories, Dreams, Relfections
  - simmer: boil slowly at low temperature
  - indignation: Phẫn nộ
  - ex: My aunt was simmering with indignation
  - uneasy (adj): bất an, khó chịu
* 08/01/2026
** Memories, Dreams, Relfections
  - abyss (n): Vực thẳm. ex: Anabyss had opened between him and me, and I saw no possibility of ever bridging it, for it was infinite in extent. 
  - Still less/ Much less: chứ đừng nói chi đến, huống chi là. ex: I had not inventedthat thought about God and the cathedral, still less the dream that had befallen me at the age of three
* 13/01/2026
** Memories, Dreams, Relfections
  - I don't give a damn for a career if it has to be based on the premise of restricting research and concealing the truth.
  - could not make (st/sb) out: Không thể hiểu nổi, không nhận ra nổi, ...
  - Bewilder (v) confuse. bewildered (adj) confused. Hoang mang. 
* 14/01/2026
** Memories, Dreams, Relfections
  - Of their/my/your ow accord: Tự nguyện. Ex: I resolved for the present not to bring any theoretical premises to bear upon them, but to wait and see what they would tell of their own accord. Tôi quyết định rằng, trước mắt, sẽ không áp đặt bất kỳ giả thuyết lý thuyết nào lên họ, mà sẽ chờ đợi và lắng nghe những gì họ tự thân kể ra.
  - be a question of something: vấn đề là, used to say what the most important fact, part, or feature of something is. Ex: I would love to come, but it’s a question of time.
* 17/01/2026
** Memories, Dreams, Relfections
  - hitherto (adv) cho đến nay. Ex: Therefore, my encounter with alchemywas decisive for me, as it provided me with the historical basiswhich I had hitherto lacked.
  - paucity (n) thiếu, khan hiếm
* 21/01/2026
** Memories, Dreams, Relfections
  - Omission (n) bỏ sót, thiếu sót. Ex: she searched the table for omissions
  - Lay aside (v) gác lại, để sang  một bên, dành dụm. Ex: In my old age in 1949 I wished to repair this omission, but wasstricken with a faint while I was buying tickets. After that, the plansfor a trip to Rome were once and for all laid aside.
  - 
* 27/01/2026
** Man and his symbols
  - One cannot afford to be naive in dealing with dreams. They originate in a spirit that is not quite human, but is rather a breath of nature —a spirit of th e beautiful and generous as well as of the cruel goddess.
* 30/01/2026
** Man and his symbols
  - "But this creatively active aspect of the psychic nucleus can come into play only when the ego gets rid of all purposive and wishful aims and tries to get to a deeper, more basic form of existence. The ego must be able to listen attentively and to give itself, without any further design or purpose, to that inner urge toward growth. Many existentialist philosophers try to describe this state, but they go only as far as stripping off the illusions of consciousness: They go right up to the door of the unconscious and then fail to open it. People living in cultures more securely rooted than our own have less trouble in understanding that it is necessary to give up the utilitarian attitude of conscious planning in order to make way for the inner growth of the personality." Đoạn này mô tả gần với những gì Krishnarmuti đã nói, và thiền trong Phật Giáo. Việc bám vào các ý tưởng, hình ảnh xuất hiện khi thiền (theo tôi nó chính là vô thức) sẽ có nguy cơ dẫn đến tẩu hỏa nhập ma, hay chứng loạn thần. 