* 03/01/2026
** Memories, Dreams, Relfections
  - For all: Despite
  - above all: most important, trên hết
  - Inception: khởi đầu
  - Conception: quan niệm/khái niệm. Thụ thai, inception of motherhood
  - It is not for me to do st: not allowed to do st
  - Fend off other obligations: Gác lại hoặc đẩy lùi các nghĩa vụ/công việc khác
  - Take the plunge: Một thành ngữ có nghĩa là quyết tâm thực hiện một việc gì đó quan trọng hoặc khó khăn sau khi đã đắn đo (quyết tâm "đâm lao").
  - In vain: Vô ích, vô vọng, không đem lại kết quả gì. I asked in vain. 
  - take (st) for granted: lẽ đương nhiên, hiển nhiên, không trân trọng
  - "Never felt any disposition to" means someone lacks the natural inclination, mood, or desire (disposition) to do something, often implying a lack of feeling, interest, or readiness, like "never felt any disposition to argue" (no desire to) or "never felt any disposition to complain" (never felt like it)
  - inexplicable: không giải thích được
* 04/01/2026
** Memories, Dreams, Relfections
  - Pretense (n): sự giả vờ
  - At most: cùng lắm, tối đa
  - dubious: mơ hồ
  - fleeting (adj): thoáng qua
* 06/01/2026
** Memories, Dreams, Relfections
  - simmer: boil slowly at low temperature
  - indignation: Phẫn nộ
  - ex: My aunt was simmering with indignation
  - uneasy (adj): bất an, khó chịu
* 08/01/2026
** Memories, Dreams, Relfections
  - abyss (n): Vực thẳm. ex: Anabyss had opened between him and me, and I saw no possibility of ever bridging it, for it was infinite in extent. 
  - Still less/ Much less: chứ đừng nói chi đến, huống chi là. ex: I had not inventedthat thought about God and the cathedral, still less the dream that had befallen me at the age of three
* 13/01/2026
** Memories, Dreams, Relfections
  - I don't give a damn for a career if it has to be based on the premise of restricting research and concealing the truth.
  - could not make (st/sb) out: Không thể hiểu nổi, không nhận ra nổi, ...
  - Bewilder (v) confuse. bewildered (adj) confused. Hoang mang. 
* 14/01/2026
** Memories, Dreams, Relfections
  - Of their/my/your ow accord: Tự nguyện. Ex: I resolved for the present not to bring any theoretical premises to bear upon them, but to wait and see what they would tell of their own accord. Tôi quyết định rằng, trước mắt, sẽ không áp đặt bất kỳ giả thuyết lý thuyết nào lên họ, mà sẽ chờ đợi và lắng nghe những gì họ tự thân kể ra.
  - be a question of something: vấn đề là, used to say what the most important fact, part, or feature of something is. Ex: I would love to come, but it’s a question of time.
* 17/01/2026
** Memories, Dreams, Relfections
  - hitherto (adv) cho đến nay. Ex: Therefore, my encounter with alchemywas decisive for me, as it provided me with the historical basiswhich I had hitherto lacked.
  - paucity (n) thiếu, khan hiếm
* 21/01/2026
** Memories, Dreams, Relfections
  - Omission (n) bỏ sót, thiếu sót. Ex: she searched the table for omissions
  - Lay aside (v) gác lại, để sang  một bên, dành dụm. Ex: In my old age in 1949 I wished to repair this omission, but wasstricken with a faint while I was buying tickets. After that, the plansfor a trip to Rome were once and for all laid aside.
  - 
* 27/01/2026
** Man and his symbols
  - One cannot afford to be naive in dealing with dreams. They originate in a spirit that is not quite human, but is rather a breath of nature —a spirit of th e beautiful and generous as well as of the cruel goddess.
* 30/01/2026
** Man and his symbols
  - "But this creatively active aspect of the psychic nucleus can come into play only when the ego gets rid of all purposive and wishful aims and tries to get to a deeper, more basic form of existence. The ego must be able to listen attentively and to give itself, without any further design or purpose, to that inner urge toward growth. Many existentialist philosophers try to describe this state, but they go only as far as stripping off the illusions of consciousness: They go right up to the door of the unconscious and then fail to open it. People living in cultures more securely rooted than our own have less trouble in understanding that it is necessary to give up the utilitarian attitude of conscious planning in order to make way for the inner growth of the personality." Đoạn này mô tả gần với những gì Krishnarmuti đã nói, và thiền trong Phật Giáo. Việc bám vào các ý tưởng, hình ảnh xuất hiện khi thiền (theo tôi nó chính là vô thức) sẽ có nguy cơ dẫn đến tẩu hỏa nhập ma, hay chứng loạn thần. 
* 31/01/2026
** Man and his symbols
  - Tôi thấy rằng những nhận xét của Carl Jung về Phật Giáo vẫn dừng lại ở mức độ bề mặt, chưa thật sự thấu đáo đến tận cùng ý nghĩa của nó. Bởi vậy, những kết luận về tính biểu tượng, những nhận xét về tôn giáo khác, ... cũng cần phải được nhìn bằng con mắt dè chừng. Nguyên lý này nên được áp dụng mọi lúc khi tiếp nhận ý kiến từ người khác, ngay cả một học giả uyên bác - đáng tin cậy, đặc biệt là những vấn đề thực sự cần sự dấn thân trải nghiệm như vấn đề tâm linh và Đạo.
* 15/02/2026
** The Portable Jung
  - Các phản úng của con người với các sự kiện có lẽ có phần nhiều là từ vô thức, đôi khi là quyết định, mang tính cưỡng chế (bảng năng)
  - Các phản ứng khi đối mặt với vô thức: "But once the unconscious contents break through into consciousness, filling it with their uncanny power of conviction, the question arises of how the individual will react. Will he be overpowered by these contents? Will he credulously accept them? Or will he reject them? (I am disregarding the ideal reaction, namely critical understanding.) The first case signifies paranoia or schizophrenia; the second may either become an eccentric with a taste for prophecy, or he may revert to an infantile attitude and be cut off from human society; the third signifies the regressive restoration of the persona.
  - 
* 24/02/2026
** The portable Jung
  - 2 kiểu hướng ngoại duy lý (the extraverted rational types - tư duy và xúc cảm) là nhìn từ góc độ chủ thể. Nếu nhìn từ góc độ người quan sát 2 kiểu người này có thể biểu hiện phi lý, đặc trưng bởi những bộc phát vô thức phi lý tính mà chủ thể không mảy may hay biết. 
  - Do đời sống mang tính duy lý, lý trí, kiểu người này có nguy cơ đàn áp các nhu cầu vô thức, và khi đến mức cực đoan có thể gây ra tình trạng bệnh lý. Vô thức bị đàn áp quay trở lại với tính nguyên thủy, trẻ con, và hỗn loạn. 
  - Bề ngoài người hướng ngoại duy lý có thể rất phù hợp chuẩn mực xã hội, trật tự, có kế hoạch, có lý do rất rõ ràng nhưng bên trong (vô thức) họ có thể trở thành nô lệ cho những thú vui bản năng (như ăn uống, dục vọng cưỡng chế) hoặc bị ám ảnh bởi những trực giác đen tối (luôn nghi ngờ, nhìn đâu cũng thấy âm mưu, độc hại).
  - Một người bề ngoài đạo mạo, đạo đức, trật tự, vững chãi (có thể anh ta cảm thấy tự nhiên như thế chứ không hẳn giả tạo) nhưng khi không còn bị xã hội quan sát, anh ta có thể có những dục vọng thấp kém cưỡng chế, sa đà vào những thứ gây nghiện, luôn cảm thấy trực giác lo lắng, bất an. (như vậy việc nghiện một thứ gì đó không chỉ đơn thuần do chất ngây nghiện, nó còn có sự tham gia phức tạp của các động cơ vô thức - việc chúng ta đơn giản hóa mọi sự, quy trách nhiệm cho một thứ đơn giản sẽ không thể giải quyết được vấn đề "nghiện" phức tạp này). 
- 
* 26/02/2026
** The Portable Jung
  - Chúng ta có thể hiểu được một trong những sai lầm lớn nhất của nền văn minh chúng ta, đó là niềm tin mang tính mê tín vào các phát biểu bằng lời, sự đánh giá quá mức vô hạn đối với việc giáo dục bằng lời nói và phương pháp. Một đứa trẻ dĩ nhiên để cho mình bị ấn tượng bởi những lời lẽ to tát của cha mẹ, nhưng có thực người ta tin rằng nó được giáo dục bởi những điều ấy không? Thực ra, chính đời sống của cha mẹ mới giáo dục đứa trẻ, còn những gì họ thêm vào bằng lời nói và cử chỉ, cùng lắm chỉ làm nó bối rối.
* 27/02/2026
** The Portable Jung
  - Khi tiếp xúc với vô thức phải cẩn thận không để nó nuốt chững, bản ngã phải giữ vai trò điều phối. Vô thức cần được *lắng nghe và phản biện* chứ không phải đồng hóa. Việc thẩm mỹ hóa và trí tuệ hóa chỉ sử dụng khi có nguy cơ mất kiểm soát, việc sử dụng chúng quá sớm sẽ ngăn chặn ta học bài học của mình. 
  - "Có một nguy cơ là bản ngã có thể, nói một cách hình tượng, mất đầu của mình, rằng nó sẽ không thể tự vệ trước áp lực của những yếu tố cảm xúc — một tình huống thực tế thường gặp ở giai đoạn khởi phát của bệnh tâm thần phân liệt. Nguy cơ này sẽ không tồn tại, hoặc sẽ không gay gắt đến thế, nếu quá trình đối diện và giải quyết với vô thức có thể bằng cách nào đó tước bỏ tính năng động của các cảm xúc. Và trên thực tế, điều này quả có xảy ra khi lập trường đối nghịch được thẩm mỹ hóa hoặc trí tuệ hóa. Nhưng sự đối diện với vô thức phải là một quá trình đa diện, bởi chức năng siêu việt không phải là một tiến trình cục bộ vận hành theo một lộ trình đã được điều kiện hóa; nó là một sự kiện toàn diện và trọn vẹn, trong đó mọi khía cạnh đều được — hoặc cần phải được — bao hàm. Do đó, cảm xúc phải được triển khai với toàn bộ sức mạnh của nó. Việc thẩm mỹ hóa và trí tuệ hóa là những vũ khí tuyệt vời để chống lại những cảm xúc nguy hiểm, nhưng chúng chỉ nên được sử dụng khi có một mối đe dọa sống còn, chứ không phải nhằm né tránh một nhiệm vụ cần thiết."
* 07/03/2026
** The portable Jung
  - Kiểu tâm lý hướng nội: Người hướng nội đề cao chủ quan (ego), xem thường đối tượng. Hệ quả là mối quan hệ với đối tượng được duy trì bằng vô thức. Kẻ xem thường tiền bạc lại phụ thuộc vào tiền bạc, kẻ nghĩ rằng mình không quan tâm người khác nghĩ gì lại vô thức cần sự công nhận, thậm chí một lời hạ thấp cũng khiến anh ta dằn vặt. Và khi đến cực đoan, những biểu hiện ấu trĩ, nguyên thủy vô thức với đối tượng xuất hiện: "Bất cứ điều gì lạ lẫm và mới mẻ đều khơi dậy nỗi sợ hãi và sự ngờ vực, như thể đang che giấu những hiểm họa không xác định; những kỷ vật gia đình và những thứ tương tự gắn chặt vào tâm hồn anh ta như bởi những sợi chỉ vô hình; bất kỳ sự thay đổi nào cũng gây khó chịu, nếu không muốn nói là thực sự nguy hiểm, vì nó dường như biểu thị một sự hoạt hóa ma thuật của đối tượng"
  - "Hệ quả từ mối quan hệ không thích nghi của cái tôi với đối tượng — vì ham muốn thống trị không phải là sự thích nghi — một mối quan hệ bù trừ nảy sinh trong vô thức, biểu hiện như một sự gắn kết tuyệt đối và không thể kiềm chế với đối tượng. Cái tôi càng đấu tranh để bảo vệ sự độc lập, sự tự do khỏi các nghĩa vụ và sự ưu việt của mình, nó càng trở nên nô lệ cho các dữ kiện khách quan. Sự tự do tâm trí của cá nhân bị xiềng xích bởi nỗi nhục nhã của sự lệ thuộc tài chính, sự tự do hành động của anh ta run rẩy trước dư luận, sự ưu việt đạo đức của anh ta sụp đổ trong một vũng lầy của những mối quan hệ thấp kém, và ham muốn thống trị của anh ta kết thúc bằng một sự thèm khát thảm hại được yêu thương. Giờ đây, chính vô thức đảm nhận mối quan hệ với đối tượng, và nó thực hiện theo cách được tính toán để đưa ảo tưởng về quyền lực và ảo tưởng về sự ưu việt đến chỗ đổ nát hoàn toàn. Đối tượng khoác lên mình những chiều kích khủng khiếp bất chấp nỗ lực có ý thức nhằm hạ thấp nó."
  - Kiểu hình Hướng nội Phi lý: "Tuy nhiên, sự bao dung này không được đi xa đến mức miễn trừ hoàn toàn cho họ nhu cầu phải giao tiếp. Điều này sẽ chỉ gây ra cho họ tổn hại lớn nhất. Chính định mệnh sẽ chuẩn bị cho họ, có lẽ còn nhiều hơn cả những người khác, những khó khăn bên ngoài ập đến dữ dội, thứ có tác dụng làm tỉnh người đối với những kẻ đang say sưa với tầm nhìn nội tại. Thường thì chỉ có một nhu cầu cá nhân mãnh liệt mới có thể vắt ra được từ họ một lời tự bạch mang tính người."
